const correctAPIReturn = {
  "login": "NatanRib",
  "id": 54828826,
  "node_id": "MDQ6VXNlcjU0ODI4ODI2",
  "avatar_url": "https://avatars.githubusercontent.com/u/54828826?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/NatanRib",
  "html_url": "https://github.com/NatanRib",
  "followers_url": "https://api.github.com/users/NatanRib/followers",
  "following_url": "https://api.github.com/users/NatanRib/following{/other_user}",
  "gists_url": "https://api.github.com/users/NatanRib/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/NatanRib/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/NatanRib/subscriptions",
  "organizations_url": "https://api.github.com/users/NatanRib/orgs",
  "repos_url": "https://api.github.com/users/NatanRib/repos",
  "events_url": "https://api.github.com/users/NatanRib/events{/privacy}",
  "received_events_url": "https://api.github.com/users/NatanRib/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Natan Ribeiro Marçal",
  "company": "TOTVS CRM",
  "blog": "https://www.linkedin.com/in/natan-mar%C3%A7al-615b35185/",
  "location": "Cândido Mota - SP",
  "email": null,
  "hireable": null,
  "bio": "Full stack Developer |\r\nFront: Dart/Flutter |\r\nBack: Java/SpringBoot",
  "twitter_username": null,
  "public_repos": 26,
  "public_gists": 0,
  "followers": 5,
  "following": 4,
  "created_at": "2019-09-03T03:34:38Z",
  "updated_at": "2021-08-04T22:54:35Z"
};

const userNotFoundAPIReturn = {
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-a-user"
};

const listOfRepositoriesTest = [
  {
    "id": 375463286,
    "node_id": "MDEwOlJlcG9zaXRvcnkzNzU0NjMyODY=",
    "name": "AltKit",
    "full_name": "jpd002/AltKit",
    "private": false,
    "owner": {
      "login": "jpd002",
      "id": 6760433,
      "node_id": "MDQ6VXNlcjY3NjA0MzM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6760433?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jpd002",
      "html_url": "https://github.com/jpd002",
      "followers_url": "https://api.github.com/users/jpd002/followers",
      "following_url": "https://api.github.com/users/jpd002/following{/other_user}",
      "gists_url": "https://api.github.com/users/jpd002/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jpd002/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jpd002/subscriptions",
      "organizations_url": "https://api.github.com/users/jpd002/orgs",
      "repos_url": "https://api.github.com/users/jpd002/repos",
      "events_url": "https://api.github.com/users/jpd002/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jpd002/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/jpd002/AltKit",
    "description": "A Swift Package that allows iOS apps to communicate with AltServer.",
    "fork": true,
    "url": "https://api.github.com/repos/jpd002/AltKit",
    "forks_url": "https://api.github.com/repos/jpd002/AltKit/forks",
    "keys_url": "https://api.github.com/repos/jpd002/AltKit/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/jpd002/AltKit/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/jpd002/AltKit/teams",
    "hooks_url": "https://api.github.com/repos/jpd002/AltKit/hooks",
    "issue_events_url": "https://api.github.com/repos/jpd002/AltKit/issues/events{/number}",
    "events_url": "https://api.github.com/repos/jpd002/AltKit/events",
    "assignees_url": "https://api.github.com/repos/jpd002/AltKit/assignees{/user}",
    "branches_url": "https://api.github.com/repos/jpd002/AltKit/branches{/branch}",
    "tags_url": "https://api.github.com/repos/jpd002/AltKit/tags",
    "blobs_url": "https://api.github.com/repos/jpd002/AltKit/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/jpd002/AltKit/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/jpd002/AltKit/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/jpd002/AltKit/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/jpd002/AltKit/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/jpd002/AltKit/languages",
    "stargazers_url": "https://api.github.com/repos/jpd002/AltKit/stargazers",
    "contributors_url": "https://api.github.com/repos/jpd002/AltKit/contributors",
    "subscribers_url": "https://api.github.com/repos/jpd002/AltKit/subscribers",
    "subscription_url": "https://api.github.com/repos/jpd002/AltKit/subscription",
    "commits_url": "https://api.github.com/repos/jpd002/AltKit/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/jpd002/AltKit/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/jpd002/AltKit/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/jpd002/AltKit/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/jpd002/AltKit/contents/{+path}",
    "compare_url": "https://api.github.com/repos/jpd002/AltKit/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/jpd002/AltKit/merges",
    "archive_url": "https://api.github.com/repos/jpd002/AltKit/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/jpd002/AltKit/downloads",
    "issues_url": "https://api.github.com/repos/jpd002/AltKit/issues{/number}",
    "pulls_url": "https://api.github.com/repos/jpd002/AltKit/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/jpd002/AltKit/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/jpd002/AltKit/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/jpd002/AltKit/labels{/name}",
    "releases_url": "https://api.github.com/repos/jpd002/AltKit/releases{/id}",
    "deployments_url": "https://api.github.com/repos/jpd002/AltKit/deployments",
    "created_at": "2021-06-09T19:07:43Z",
    "updated_at": "2021-07-05T16:35:31Z",
    "pushed_at": "2021-07-05T16:35:29Z",
    "git_url": "git://github.com/jpd002/AltKit.git",
    "ssh_url": "git@github.com:jpd002/AltKit.git",
    "clone_url": "https://github.com/jpd002/AltKit.git",
    "svn_url": "https://github.com/jpd002/AltKit",
    "homepage": null,
    "size": 16,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Swift",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 149477702,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNDk0Nzc3MDI=",
    "name": "boost-cmake",
    "full_name": "jpd002/boost-cmake",
    "private": false,
    "owner": {
      "login": "jpd002",
      "id": 6760433,
      "node_id": "MDQ6VXNlcjY3NjA0MzM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6760433?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jpd002",
      "html_url": "https://github.com/jpd002",
      "followers_url": "https://api.github.com/users/jpd002/followers",
      "following_url": "https://api.github.com/users/jpd002/following{/other_user}",
      "gists_url": "https://api.github.com/users/jpd002/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jpd002/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jpd002/subscriptions",
      "organizations_url": "https://api.github.com/users/jpd002/orgs",
      "repos_url": "https://api.github.com/users/jpd002/repos",
      "events_url": "https://api.github.com/users/jpd002/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jpd002/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/jpd002/boost-cmake",
    "description": "Easy Boost integration in CMake projects",
    "fork": true,
    "url": "https://api.github.com/repos/jpd002/boost-cmake",
    "forks_url": "https://api.github.com/repos/jpd002/boost-cmake/forks",
    "keys_url": "https://api.github.com/repos/jpd002/boost-cmake/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/jpd002/boost-cmake/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/jpd002/boost-cmake/teams",
    "hooks_url": "https://api.github.com/repos/jpd002/boost-cmake/hooks",
    "issue_events_url": "https://api.github.com/repos/jpd002/boost-cmake/issues/events{/number}",
    "events_url": "https://api.github.com/repos/jpd002/boost-cmake/events",
    "assignees_url": "https://api.github.com/repos/jpd002/boost-cmake/assignees{/user}",
    "branches_url": "https://api.github.com/repos/jpd002/boost-cmake/branches{/branch}",
    "tags_url": "https://api.github.com/repos/jpd002/boost-cmake/tags",
    "blobs_url": "https://api.github.com/repos/jpd002/boost-cmake/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/jpd002/boost-cmake/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/jpd002/boost-cmake/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/jpd002/boost-cmake/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/jpd002/boost-cmake/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/jpd002/boost-cmake/languages",
    "stargazers_url": "https://api.github.com/repos/jpd002/boost-cmake/stargazers",
    "contributors_url": "https://api.github.com/repos/jpd002/boost-cmake/contributors",
    "subscribers_url": "https://api.github.com/repos/jpd002/boost-cmake/subscribers",
    "subscription_url": "https://api.github.com/repos/jpd002/boost-cmake/subscription",
    "commits_url": "https://api.github.com/repos/jpd002/boost-cmake/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/jpd002/boost-cmake/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/jpd002/boost-cmake/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/jpd002/boost-cmake/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/jpd002/boost-cmake/contents/{+path}",
    "compare_url": "https://api.github.com/repos/jpd002/boost-cmake/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/jpd002/boost-cmake/merges",
    "archive_url": "https://api.github.com/repos/jpd002/boost-cmake/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/jpd002/boost-cmake/downloads",
    "issues_url": "https://api.github.com/repos/jpd002/boost-cmake/issues{/number}",
    "pulls_url": "https://api.github.com/repos/jpd002/boost-cmake/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/jpd002/boost-cmake/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/jpd002/boost-cmake/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/jpd002/boost-cmake/labels{/name}",
    "releases_url": "https://api.github.com/repos/jpd002/boost-cmake/releases{/id}",
    "deployments_url": "https://api.github.com/repos/jpd002/boost-cmake/deployments",
    "created_at": "2018-09-19T16:07:53Z",
    "updated_at": "2018-09-20T13:26:19Z",
    "pushed_at": "2018-09-20T13:58:34Z",
    "git_url": "git://github.com/jpd002/boost-cmake.git",
    "ssh_url": "git@github.com:jpd002/boost-cmake.git",
    "clone_url": "https://github.com/jpd002/boost-cmake.git",
    "svn_url": "https://github.com/jpd002/boost-cmake",
    "homepage": null,
    "size": 79,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CMake",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
    },
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
];